kind: pipeline
name: default

steps:
- name: docker publish
  image: plugins/docker
  settings:
    repo: ferdavs/drone-nomad
    dockerfile: docker/Dockerfile.alpine
    tags:
      - '1.0'
      - 'latest'
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
